Window.SetBackgroundTopColor(0, 0, 0);
Window.SetBackgroundBottomColor(0, 0, 0);

logo.image = Image("arkos-logo.png");
logo.sprite = Sprite(logo.image);
logo.x = Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2;
logo.y = Window.GetHeight() / 2 - logo.image.GetHeight() / 2;
logo.sprite.SetPosition(logo.x, logo.y, 10);

message_sprite = Sprite();
message_sprite.SetPosition(Window.GetWidth() / 2 - 60, logo.y + logo.image.GetHeight() + 20, 10);

fun refresh_callback() {
  message_sprite.SetImage(Image.Text("Starting ArkOS...", 1, 1, 1));
}
Plymouth.SetRefreshFunction(refresh_callback);
