#!/bin/sh
set -e

lb config noauto \
    --distribution jammy \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --archive-areas "main restricted universe multiverse" \
    --debian-installer none \
    --iso-application "ArkOS" \
    --iso-volume "ArkOS" \
    --iso-publisher "ArkOS Project" \
    "${@}"
